script:
- |
  git config user.name "$USERNAME"
  git config user.email "$EMAIL"
  git remote remove origin
  echo "Removed origin"
  git remote add origin https://$GITHUB_API_KEY@github.com/igniuss/HomebrewAPI-wiki.git > /dev/null 2>&1
  git remote add upstream https://$GITHUB_API_KEY@github.com/copybugpaste/HomebrewAPI.wiki.git > /dev/null 2>&1
  echo "Added origin and upstream"
  git fetch origin
  git fetch upstream
  git merge upstream/master --no-edit
  echo "merged upstream/master --no-edit"
  git push origin HEAD:master
  git push upstream HEAD:master
  echo "All done!"