script:
- |
  git config user.name "Igniuss"
  git config user.email "slava_be@hotmail.com"
  git remote remove origin
https://
  git remote add origin https://$GITHUB_API_KEY@github.com/copybugpaste/HomebrewAPI-wiki.git > /dev/null 2>&1
  git remote add upstream https://$GITHUB_API_KEY@github.com/copybugpaste/HomebrewAPI.wiki.git > /dev/null 2>&1
  git fetch origin
  git fetch upstream
  git merge upstream/master --no-edit
  git push origin HEAD:master > /dev/null 2>&1
  git push upstream HEAD:master > /dev/null 2>&1